language: node_js
install:
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: Wloe83/WUKoieYVcLuerB3x6pn5hw6MuZckEMeAbr6iZFdUT/LExvQRETecj2HFDIh0Piiyg1Sfb1x+ZN5b+Gw1FVCF0lcePEYsn8/UJBMrbuQLZmSAuQUyMUH8sFf/AWVj/F9utRdxSAqvUImmY/ihxWIrUjmUypVfjEJLZ3844w+8/pguKwjQp/P4y8XBPRKo5RdQWt0aVfaPyWiIFHvhz8BBEZWVe/opM1rn738l2agZNiaxbFSYBuZNRYM1ITrL+HZN+zPArxHz2aZvIDFfrs4Jwxruf1kZrIrcRA1nrl3nMgAS9I2WV8mWz2+02cv022QZs24cb8W8XXZ8bFPuCaByRK7kamxyNzt2lrWqVRRo2qB1+17dncUgiIQDdD73U8GNl/Z/wRxlDWOtAXTx8jUPIkeXvOX0LlBjwSBW8C5udTWNTSsxGM6apnsZFtfIOLdaH3zsZyOYQAmbxgQMPaEmmA1GE5GwqXD6k5kJc2BnKnLiiRHJIH4YiltftPhWpIM+EBXnmNd6WhLtu7oPUWAqnPeZW46yAZPO2vOiCU1Z58veloVS/ekgXN7l2Sqvm5Z5PI/ADIFI2Ak3ZEQhxMeIpfVVc4qrh8WKs9hPY5yDMHNMHck94FmMyN/BZ/KP+ysh9/NRvUfhPoo7naHGnLEmDM3+4jAhH0onrqvQ=
